### PR TITLE
Update and rename 2015-01-22-uk-brands-vegan-lists.markdown to June 2…

### PR DESCRIPTION
**Pull request by Equilibriums**
…016 Vegan

### CODE REVIEW

**Comment by scottrobertson** [comment]
Oops I should not have merged that File name is broken.

**Comment by Equilibriums** [comment]
Semi afk at the moment. Will be around a bit later.

**Comment by scottrobertson** [comment]
I managed to sort it on my phone :)

**Comment by Equilibriums** [comment]
Do you  program as a hobby, freelance or for a company btw?

**Comment by scottrobertson** [comment]
All 3 :D

**Pull request merged**
